### ISSUE TITLE
solve for trick in progress?

### ISSUE THREAD

**Issue by pmbethe09** [dds-bridge/dds#103]
I was hoping to use DDS to solve for a trick after some cards are played.

Example:  https://github.com/pmbethe09/dds-test/blob/master/test_dds.cpp
```
      KJ
      -
      5
      -
97         QT
9           -
-            -
-            T
      5
      -
      A
      9
```
At NT, South leads.  DDS of course indicates that the DA takes 3 tricks (by squeezing E).

But what I want to do is solve from W or E's perspective, after S leads the DA that all plays lead to 0 tricks.
I have tried:
* setting currentTrickSuit[0]
* setting currentTrickSuit[0] and removing the DA
* setting currentTrickSuit[0], removing the DA, first = WEST

But all roads lead to "currentTrickSuit or currentTrickRank has wrong data"

Am I missing something, or does the library not support this?

**Comment by pmbethe09** [comment]
Update:  I had mistakenly assumed that currentTrickRank was the same 'Holding' encoding as remainCards, rather than just a number in [2,14]

That fixes the error, but the output continues to be for the leader -- that is setting currentTrickSuit seems to have no effect on the output from SolveBoardPBN

**Comment by tomc** [comment]
Isn't the E-W tricks just (num of cards) - (num of N-S tricks)? 

I haven't played with the library much, just a bystander comment.

**Comment by pmbethe09** [comment]
Not exactly what I am asking about.

Suppose in this example you are West and South has already lead the DA.
You want to play whichever of S9, S7, H9 produces the most tricks for your side.
(It turns out 0 is the answer for all).

When you ask DDS to solve this it tells you that the DA by South produces all 3 tricks.  But what I want to ask is, if I am W and S has already decided to lead the DA, what are the results for each card.  I cannot find a way to do that as-is.

**Comment by sorenhein** [comment]
Sorry for the late reply.  It is indeed possible.  The format is a very old DDS one.  You have to remove the diamond ace from remainCards, so something like

  dlPBN.trump = 4; // NT
  dlPBN.first = 2; // South

  dlPBN.currentTrickSuit[0] = 2; // Diamonds
  dlPBN.currentTrickSuit[1] = 0;
  dlPBN.currentTrickSuit[2] = 0;

  dlPBN.currentTrickRank[0] = 14; // Ace
  dlPBN.currentTrickRank[1] = 0;
  dlPBN.currentTrickRank[2] = 0;

  strcpy(dlPBN.remainCards, "N:KJ..5. QT...T 5...9 97.9..");

  target = -1;
  solutions = 3;
  mode = 0;
  res = SolveBoardPBN(dlPBN, target, solutions, mode, &fut2, 0);

**Comment by pmbethe09** [comment]
thank you.  Apparently when I realized that this should
dlPBN.currentTrickRank[0] =14

rather than 1<<14 I didn't go back and: 
* set currentTrickRank, currentTrickSuit
* remove the DA from remainCards

It is now working for me and I have updated my example.
