### ISSUE TITLE
Incorrect SolveBoard for  N:42.K953.Q6.96432 Q3.AT7.JT875.AQT KJ8765.J6.A43.87 AT9.Q842.K92.KJ5 in NT contract

### ISSUE THREAD

**Issue by mmilen** [dds-bridge/dds#116]
Hi,

I came across this hand. 

[Dealer "N"]
[Vulnerable "None"]
[Deal "N:42.K953.Q6.96432 Q3.AT7.JT875.AQT KJ8765.J6.A43.87 AT9.Q842.K92.KJ5"]

The contract is 3NT by West, on S4 lead SolveBoard returns 9 declarer tricks, when in fact if South plays a low spade to the first trick declarer can take max 8.

**Comment by mortensp** [comment]
Sorry but you got it wrong. There is still 9 tricks. West plays a lille diamond to the king, catches 3 clubs and south can not afford to throw a diamond or heart, so must throw a spade. West now take the Ace of spades and play a diamond. If North wins the Queen of diamonds, she can take 2 clubs and must the open hearts  => 9 tricks. If South overtakes with the Ace of diamonds, then East has 3 diamond tricks => 9 tricks.

**Comment by mmilen** [comment]
Thank you, that revealed an interesting bug in our application :).
