### ISSUE TITLE
Naming of doc files

### ISSUE THREAD

**Issue by Afwas** [dds-bridge/dds#21]
I am in the final stages of converting the main DLL doc to markdown. I noticed that the current docs have filenames with the version in them, like DLL-dds_28_x.rtf.
It seems to me this is wrong. The content in the repo should always be "current" and some git-history magic could reveal past versions.
Reaming files in git is cumbersum so I guess the old files are removed and new ones added. This makes version history difficult.
My suggestion would be renaming once more, making them a bit more desciptive in te process and keep the names as they are.

dll-description.<suffix>
algorithm.<suffix>
par-calulation.<suffix>
performing-benchmarking.<suffix>

**Comment by sorenhein** [comment]
Somehow they crop up once in a while, but it seems clean for now.

**Comment by sorenhein** [comment]
To be fixed in v2.8.3 which is in progress.
