### ISSUE TITLE
Remove all ^M (carriage return) from source files

### ISSUE THREAD

**Issue by hostilefork** [dds-bridge/dds#3]
Windows and Linux/OSX differ on the convention of whether newlines are signified by CR or CR LF.

There are some files checked in at the moment which have ^M in them, because someone (me) didn't check over it before committing them.

![screen shot 2014-11-25 at 12 39 29 pm](https://cloud.githubusercontent.com/assets/20440/5188182/f1f2fc96-74a0-11e4-8a6c-79c33242fb1f.png)

So we should remedy this.  I am not rewriting the history again, so we'll have to do this in the "conventional" way...

**Comment by sorenhein** [comment]
Somehow this crops up once in a while, but it seems clean for now.
