### ISSUE TITLE
Negative score from SolveBoard

### ISSUE THREAD

**Issue by danvk** [dds-bridge/dds#48]
I built a small wrapper around `SolveBoard`. I'm getting negative scores out of it. How should I interpret this? If I have zero or one cards played in the first trick, the scores make sense to me (they're 9 or 4 depending on whose play it is).

```
$ ./next-plays "N:T843.K4.KT853.73 J97.J763.642.KJ5 Q52.Q982.QJ.9862 AK6.AT5.A97.AQT4" N W 5D 2D
dl.first: 0
dl.trump: 4
dl.remainCards[0][0]: 0x518
dl.remainCards[0][1]: 0x2010
dl.remainCards[0][2]: 0x2508
dl.remainCards[0][3]: 0x88
dl.remainCards[1][0]: 0xa80
dl.remainCards[1][1]: 0x8c8
dl.remainCards[1][2]: 0x50
dl.remainCards[1][3]: 0x2820
dl.remainCards[2][0]: 0x1024
dl.remainCards[2][1]: 0x1304
dl.remainCards[2][2]: 0x1800
dl.remainCards[2][3]: 0x344
dl.remainCards[3][0]: 0x6040
dl.remainCards[3][1]: 0x4420
dl.remainCards[3][2]: 0x4280
dl.remainCards[3][3]: 0x5410
dl.currentTrickSuit[0]: 2
dl.currentTrickRank[0]: 5
dl.currentTrickSuit[1]: 2
dl.currentTrickRank[1]: 2
dl.currentTrickSuit[2]: 0
dl.currentTrickRank[2]: 0
[
  {"suit": "D", "rank": "Q", "score": -2},
  {"suit": "D", "rank": "J", "score": -2}
]
```

Full code in [this gist][1]

[1]: https://gist.github.com/danvk/0e298b7bbb80f5fceaf1

**Comment by danvk** [comment]
(this seems to happen when there's only one play, or only logically equivalent plays)

**Comment by Afwas** [comment]
I think you found something and so did I. This is the culprit in SolverIF.cpp lines 304 - 321:
```
  // ----------------------------------------------------------
  // mode == 0: Check whether there is only one possible move
  // ----------------------------------------------------------

  if (mode == 0 && noMoves == 1)
  {
    moveType * mp = thrp->moves.MakeNextSimple(trick, handRelFirst);

    futp->nodes = 0;
    futp->cards = 1;

    futp->suit[0] = mp->suit;
    futp->rank[0] = mp->rank;
    futp->equals[0] = mp->sequence << 2;
    futp->score[0] = -2;

    goto SOLVER_DONE;
  }
```
Note that the score is set to -2.

I have no idea what the use of this snippet is. I found in the docs:
> Note: mode no longer always has this effect internally in DDS. We think mode is no longer useful, and > we may use it for something else in the future. If you think you need it, let us know!
So we can add that mode can be buggy.

A solution for you is to set mode to 2. That solves it in my tests. (Yes, I did confirm your observation with a SolveBoardPBN implementation of your deal).

Have fun

**Comment by danvk** [comment]
Thanks for the reply. Reading the [docs][1] for `SolveBoard` and mode, I see that this behavior is explicitly documented:

> Do not search to find the core if the hand to play has only one card, including its equivalents, to play. Score is set to –2 for this card, indicating that there are no alternative cards. If there are multiple choices for cards to play, search is done to find the score. This mode is very fast but you don't always search to find the score.

So it seems that setting `mode=2` is exactly what I want. I'll close this out since it's expected behavior, but it does seem like `mode=2` should be the default.

[1]: https://github.com/dds-bridge/dds/blob/develop/doc/dll-description.md#functions

**Comment by danvk** [comment]
In case anyone else reads this: never use `mode=2`. Use `mode=1` instead. `mode=2` will give incorrect results without warning. For example, with `mode=2` if you call `SolveBoard` twice with the same board, first in no trump and then in spades, you'll get the no trump results back for both calls. Calling `SolveBoard` with `mode=1` will give the correct results.
