### ISSUE TITLE
Simple comment fix for hands.h. 

### ISSUE THREAD

**Issue by rewolff** [dds-bridge/dds#58]
Attached a simple fix in the comments of "hands.h". 

The spades/hearts/diamonds/clubs comments were marking the hands for north, east, south, and west. 

Github does not allow me to attach a ".patch" file, so I need to rename it to .txt 

[hand_fix.txt](https://github.com/dds-bridge/dds/files/170556/hand_fix.txt)

**Comment by sorenhein** [comment]
Thanks
