### ISSUE TITLE
makedepend warnings?

### ISSUE THREAD

**Issue by rop49** [dds-bridge/dds#61]
Hi.
I'm not very familiar with c-programming, just trying to build the library :)
Using cygwin, when I run: make depend
I get a list of warnings.
Are these OK to ignore, or am I missing some configuration or setup?

makedepend: warning:  dds.cpp (reading dds.h, line 13): cannot find include file "stdio.h"
makedepend: warning:  dds.cpp (reading dds.h, line 14): cannot find include file "stdlib.h"
makedepend: warning:  dds.cpp (reading dds.h, line 15): cannot find include file "string.h"
makedepend: warning:  dds.cpp (reading dds.h, line 16): cannot find include file "time.h"
makedepend: warning:  dds.cpp (reading dds.h, line 17): cannot find include file "assert.h"
makedepend: warning:  dds.cpp (reading dds.h, line 18): cannot find include file "math.h"
makedepend: warning:  dds.cpp (reading TransTable.h, line 19): cannot find include file "stdio.h"
makedepend: warning:  dds.cpp (reading TransTable.h, line 20): cannot find include file "stdlib.h"
makedepend: warning:  dds.cpp (reading TransTable.h, line 21): cannot find include file "string.h"
makedepend: warning:  dds.cpp (reading Timer.h, line 41): cannot find include file "stdio.h"
makedepend: warning:  dds.cpp (reading Timer.h, line 42): cannot find include file "string.h"
makedepend: warning:  dds.cpp (reading Timer.h, line 43): cannot find include file "time.h"
makedepend: warning:  dds.cpp (reading Timer.h, line 44): cannot find include file "inttypes.h"
makedepend: warning:  dds.cpp (reading Timer.h, line 49): cannot find include file "sys/time.h"
makedepend: warning:  dds.cpp (reading ABstats.h, line 13): cannot find include file "stdio.h"
makedepend: warning:  dds.cpp (reading ABstats.h, line 14): cannot find include file "stdlib.h"
makedepend: warning:  dds.cpp (reading ABstats.h, line 15): cannot find include file "string.h"
makedepend: warning:  dds.cpp (reading Moves.h, line 13): cannot find include file "stdio.h"
makedepend: warning:  dds.cpp (reading Moves.h, line 14): cannot find include file "stdlib.h"
makedepend: warning:  dds.cpp (reading Moves.h, line 15): cannot find include file "string.h"
makedepend: warning:  dds.cpp (reading Scheduler.h, line 13): cannot find include file "stdio.h"
makedepend: warning:  dds.cpp (reading Scheduler.h, line 14): cannot find include file "stdlib.h"
makedepend: warning:  dds.cpp (reading Scheduler.h, line 15): cannot find include file "string.h"
makedepend: warning:  dds.cpp (reading Scheduler.h, line 16): cannot find include file "time.h"
makedepend: warning:  dds.cpp (reading Scheduler.h, line 21): cannot find include file "sys/time.h"
makedepend: warning:  CalcTables.cpp, line 11: cannot find include file "stdexcept"
makedepend: warning:  Moves.cpp, line 11: cannot find include file "stdexcept"
makedepend: warning:  Par.cpp, line 11: cannot find include file "stdexcept"
makedepend: warning:  SolverIF.cpp, line 10: cannot find include file "stdexcept"
makedepend: warning:  Stats.cpp, line 10: cannot find include file "stdexcept"
makedepend: warning:  Stats.cpp, line 18: cannot find include file "time.h"
makedepend: warning:  Stats.cpp, line 27: cannot find include file "sys/time.h"
makedepend: warning:  Timer.cpp, line 15: cannot find include file "stdexcept"
makedepend: warning:  TransTable.cpp, line 10: cannot find include file "stdexcept"

**Comment by Afwas** [comment]
Copy the makefile you need (probably /src/makefiles/Makefile_cygwin) to the /src folder. Then run make from the /src folder.

**Comment by rop49** [comment]
Yes, I did take a copy of Makefile_cygwin before make, as per the instructions, so that should be OK.

**Comment by Afwas** [comment]
make -f Makefile_cygwin

**Comment by rop49** [comment]
I did instead

cp Makefiles/Makefile_cygwin ./Makefile

but should be same thing...

**Comment by Afwas** [comment]
^ yes

**Comment by Afwas** [comment]
https://stackoverflow.com/questions/27824139/cygwin-gcc-cannot-find-stdio-h
