### ISSUE TITLE
Cannot get dtest to work under cygwin

### ISSUE THREAD

**Issue by rop49** [dds-bridge/dds#62]
I try the following under cygwin:

cd test 
make clean
cd ../src
make clean
make depend   # with warnings
make
make install
cd ../test
make depend # with warnings
make
./dtest.exe
./dtest.exe list10.txt calc 1

But I dont get any output at all.
To debug, I put a printf line first in the main() function, but still no output, so it does not seem rech main() at all, but just exits.
The exit-code is 0.

Any idea how to troubleshoot this?
I am running on Win-10 -- have you tested this platform?

**Comment by Afwas** [comment]
Copy the makefile you need into the /test folder. Then run make.
As an aside: if you want some output try some functions from the examples page.

**Comment by rop49** [comment]
Thanks Afwas. Yes, I also have copied the Makefiles, according to instructions -- forgot to mention that.

**Comment by rop49** [comment]
In the examples directory, I did:

cp Makefiles/Makefile_cygwin ./Makefile
make CalcDDtable
./CalcDDtable

Same result:
No output
exitcode=0

What is going on? :)

**Comment by Afwas** [comment]
Is there a dds.dll (or similar) in the /examples folder? That should be created when you run make inside /src folder.

**Comment by rop49** [comment]
Yes, the 
make install
copied dds.dll and dds.def
to /test and /examples
so that is OK.

I get no build errors, so everything seems ok, except nothing happens when I run .exe file.

**Comment by Afwas** [comment]
You have installed g++ properly? See for example http://cs.calvin.edu/curriculum/cs/112/resources/installingEclipse/cygwin/

**Comment by rop49** [comment]
Yep, looks OK, too. 
I have 

gcc-g++
make
makedepend

installed.
Not gdb, but I think is not relevant here...
I can try that too, and see.

**Comment by rop49** [comment]
Installed gdb, too, and rebuilt everything. But didnt change anything, same result.

**Comment by Afwas** [comment]
https://stackoverflow.com/questions/27824139/cygwin-gcc-cannot-find-stdio-h

**Comment by rop49** [comment]
Thanks Afwas. Everything looks ok here with that link, too?

But have you tested the cygwin-build under Win-10? 
There are some tricky issues sometimes with permissions, etc... 

Strange I dont get any build-errors or non-0 exit-codes, though.....

**Comment by Afwas** [comment]
I'd have to install Windows to run cygwin. I might find some time after the weekend to set things up.

**Comment by rop49** [comment]
OK :)
I will also give it a shot with Visual C++ and/or Mingw compiler.

**Comment by Afwas** [comment]
Works fine here (cygwin64 on Win10).
- I installed the complete Devel tree in cygwin
- I needed to copy dds.dll to /examples
Attached the session
[cygwin_session.txt](https://github.com/dds-bridge/dds/files/250947/cygwin_session.txt)

**Comment by rop49** [comment]
Thanks Afwsa --- OK, will try full Devel, too, then.

Just checking my understanding here...
I didnt find windres and cvtres on my system.
In the Makefile header-text it says:

    # The "windres" and "cvtres" tools are used for putting version
    # information into the DLL in a way that Windows can see.
    # It is not mandatory, and if you don't have those tools,
    # You can remove $(VFILE).obj in the target line below.

What does this mean exactly?

I understood it as changing the line:
    O_FILES = $(subst .cpp,.o,$(SOURCE_FILES)) $(VFILE).o
to this:
    O_FILES = $(subst .cpp,.o,$(SOURCE_FILES))

Is that correctly understood?
Or did I make a mistake there?

**Comment by rop49** [comment]
So weird ----- I now rebuilt everything with mingw.

Build goes fine, but when I start dtest.exe I still get exactly the same result. No output. exitcode=0.

How frustrating..... :(

**Comment by rop49** [comment]
Now rebuilt with cygwin64, full Devel, too -- still same useless result.
Here also how it looks when I run from gdb -- immediately exits with no output.

$ file dtest.exe
dtest.exe: PE32+ executable (GUI) x86-64, for MS Windows

$ gdb dtest.exe
GNU gdb (GDB) (Cygwin 7.10.1-1) 7.10.1
...
(gdb) run
Starting program: dtest.exe
[New Thread 3844.0x14e8]
[New Thread 3844.0x16f8]
[New Thread 3844.0xebc]
[New Thread 3844.0xb5c]
[New Thread 3844.0xf10]
[Thread 3844.0xb5c exited with code 0]
[Thread 3844.0xebc exited with code 0]
[Thread 3844.0xf10 exited with code 0]
[Inferior 1 (process 3844) exited normally]
(gdb)

**Comment by Afwas** [comment]
- I needed to copy dds.dll into /test

[cygwin_session_dtest.txt](https://github.com/dds-bridge/dds/files/251259/cygwin_session_dtest.txt)

**Comment by rop49** [comment]
Yesw, I know -- otherwise the make job will throw error: 
  ld: cannot find -ldds

From the src directory, you can also do 
make install
which will copy the files for you.

**Comment by rop49** [comment]
Now tried with Visual-C++, too....
Lo and behold.... that worked!
What an ordeal.... :)

**Comment by boput** [comment]
I have the exactly the same problem (Win 10 Pro 64 bit, cygwin64); dds compiles without errors, but there is no output (in test, or example folder). On the same machine, same cygwin64, compiling simple HelloWorld.c program produces required output: Hello World!

**Comment by sorenhein** [comment]
Sorry for your trouble.  It should indeed work as described in the first message, and it does on my system.  If somebody finds something to change in the DDS set-up, let us know.  (v2.9.0 will be a bit different with regard to make depend.)
