### ISSUE TITLE
Number of tricks makeable by West for each possible opening lead

### ISSUE THREAD

**Issue by gopalkriagg** [dds-bridge/dds#64]
I am making a project, part of which is to calculate given 1000s of deals with a same (fixed) West hand, calculate percentage time West is able to defeat the contract using dds (Assume South is declarer, hands are according to bidding sequence 1NT(by South) - Pass - 3NT - Pass - Pass - Pass)
I have tried to use SolveAllBoard with this:
```
bo.deals[handno].trump = NOTRUMP;
bo.deals[handno].first = WEST;
```
and
```
bo.target [handno] = -1;
bo.solutions[handno] = 3;
bo.mode [handno] = 0;
```
and it gives me score for each of the 13 cards of West's hand. Is this correct way to do it?
Sorry, if it is silly I don't have much experience with Contract bridge.

**Comment by sorenhein** [comment]
Sorry for late response.  If you just want one optimum card and the score, you can use solutions == 1.  Otherwise it's fine what you do.
