### ISSUE TITLE
Implementation relies on char==signed char

### ISSUE THREAD

**Issue by fvannee** [dds-bridge/dds#65]
I was trying to compile and run DDS for an Android device with the Android NDK.
Everything compiles fine, but I was getting invalid memory access exceptions at run-time.
It turns out that the DDS implementation defines type 'char' in some structs and then assigns '-1' to it. (Init.cpp SetDealTables() for example).
Many compilers treat char's by default as signed, thus assigning '-1'. However, this is something compiler-specific and not in the standard (see: http://stackoverflow.com/questions/2054939/is-char-signed-or-unsigned-by-default). The g++ and clang compilers for the Android NDK are configured to treat them as unsigned. Thus, effectively assigning 255 to the char.
This gives issues when at a later point the 'char' is assigned to an 'int'. The int now has value 255 instead of the expected -1. This crashes the program later on.

For me, the following fixed the issue:

//dds.h
struct absRankType // 2 bytes
{
  char rank;
  signed char hand; // signed char instead of char
};

However, there could be more situations where a signed char is meant instead of an undefined (signed/unsigned) char. Perhaps these could be changed as well.

**Comment by sorenhein** [comment]
Excellent report!  I think you got the only one :-)
