### ISSUE TITLE
Wrong results

### ISSUE THREAD

**Issue by eknkcc** [dds-bridge/dds#66]
I am calling dll functions from c# and giving correct parameters (checked many times) but I am getting different results than other programs which uses Bo Haglund DDS. Such as http://mirgo2.co.uk/bridgesolver/ or Magic Contest. I tried SolveBoard and SolveBoardPBN methods..  What can cause this problem ?

**Comment by eknkcc** [comment]
I solved the issue by using CalcDDTable method. I still couldnt understand why SolveBoard and SolveBoardPBN methods giving different results. But CalcDDTable returned correct results. Maybe I misunderstood the purpose of SolveBoard method.

**Comment by rewolff** [comment]
With a bug like this, giving a sample hand, that produces the different results e.g. a one line PBN would help. You can explain what you're seeing, and other can try to reproduce that, or in this case probably explain WHY you're getting different results.

**Comment by sorenhein** [comment]
Sorry for the late response.  I'm going to go out on a limb and assume that there was a problem in calling correctly, so I'm closing the issue.  If not, or if you have a suggestion for the documentation, let me know.  There are examples in the "examples" directory.
