### ISSUE TITLE
Build problem on raspberry pi

### ISSUE THREAD

**Issue by bkoblenz** [dds-bridge/dds#75]
I am trying to build a program that is dependent on dds on a Raspberry Pi running Debian.

I seem to have a problem with -mtune=generic from your makefile.  Suggestions?

pi@Master-198:~ $ sudo python -mpip install --user git+https://github.com/anntzer/redeal
Downloading/unpacking git+https://github.com/anntzer/redeal
Cloning https://github.com/anntzer/redeal to /tmp/pip-z1N6Rs-build
Running setup.py (path:/tmp/pip-z1N6Rs-build/setup.py) egg_info for package from git+https://github.com/anntzer/redeal

Requirement already satisfied (use --upgrade to upgrade): colorama>=0.2.4 in /usr/lib/python2.7/dist-packages (from redeal==0.2.0)
Downloading/unpacking enum34>=1.0.4 (from redeal==0.2.0)
Downloading enum34-1.1.6-py2-none-any.whl
Installing collected packages: enum34, redeal
Running setup.py install for redeal
g++ -fPIC -g -O3 -flto -fopenmp -mtune=generic -Wno-write-strings -Wshadow -Wsign-conversion -pedantic -Wall -Wextra -Wcast-align -Wcast-qual -Wctor-dtor-privacy -Wdisabled-optimization -Winit-self -Wlogical-op -Wmissing-declarations -Wmissing-include-dirs -Wnoexcept -Wold-style-cast -Woverloaded-virtual -Wredundant-decls -Wsign-promo -Wstrict-null-sentinel -Wstrict-overflow=1 -Wswitch-default -Wundef -Werror -Wno-unused -Wno-unknown-pragmas -Wno-long-long -Wno-format -c dds.cpp
g++: error: unrecognized argument in option ‘-mtune=generic’
g++: note: valid arguments to ‘-mtune=’ are: arm1020e arm1020t arm1022e arm1026ej-s arm10e arm10tdmi arm1136j-s arm1136jf-s arm1156t2-s arm1156t2f-s arm1176jz-s arm1176jzf-s arm2 arm250 arm3 arm6 arm60 arm600 arm610 arm620 arm7 arm70 arm700 arm700i arm710 arm7100 arm710c arm710t arm720 arm720t arm740t arm7500 arm7500fe arm7d arm7di arm7dm arm7dmi arm7m arm7tdmi arm7tdmi-s arm8 arm810 arm9 arm920 arm920t arm922t arm926ej-s arm940t arm946e-s arm966e-s arm968e-s arm9e arm9tdmi cortex-a12 cortex-a15 cortex-a15.cortex-a7 cortex-a5 cortex-a53 cortex-a57 cortex-a57.cortex-a53 cortex-a7 cortex-a8 cortex-a9 cortex-m0 cortex-m0plus cortex-m1 cortex-m3 cortex-m4 cortex-r4 cortex-r4f cortex-r5 cortex-r7 ep9312 fa526 fa606te fa626 fa626te fa726te fmp626 generic-armv7-a iwmmxt iwmmxt2 marvell-pj4 mpcore mpcorenovfp native strongarm strongarm110 strongarm1100 strongarm1110 xscale
Makefiles/Makefile_linux_shared:96: recipe for target 'dds.o' failed
make: *** [dds.o] Error 1

**Comment by Afwas** [comment]
Try
-march=native
Else for the RPi2 I think the cortex-a7 but you can leave out this line in the Makefile.

**Comment by bkoblenz** [comment]
Thank you, but my problem is compounded by the fact that dds is downloaded
and built automatically through a setup.py method that generates an
executable via pip install.

I dont know how to intercept this process where I can actually change the
sources since it is all done through /tmp directories that are cleaned up.

**Comment by anntzer** [comment]
Perhaps the makefiles could include $(CFLAGS) at the end of $(COMPILE_FLAGS) to make it easier to override without manual edition of the makefiles?

**Comment by zdraganov** [comment]
You can run it in Docker if possible in your scenario.

**Comment by sorenhein** [comment]
Sorry for the late reply. If someone can provide a Makefile suitable for this setup (together with a description of the setup), I will gladly add it to the DDS distribution.
