### ISSUE TITLE
Signedness in the public API

### ISSUE THREAD

**Issue by maliberty** [dds-bridge/dds#81]
The public API has some functions that would seem to more natural take unsigned ints, eg

EXTERN_C DLLEXPORT void STDCALL SetMaxThreads(int userThreads);
EXTERN_C DLLEXPORT int STDCALL SetThreading(int code);
EXTERN_C DLLEXPORT void STDCALL SetResources(int maxMemoryMB, int maxThreads);

A negative number of threads or memory is nonsensical.   Are you ok with changing the public API to be unsigned where appropriate or are you trying to maintain stability?  I am glad to work up a pull request if you would allow the change.

Similarly with various structures, eg

struct boards
{
  int noOfBoards;
...
}

**Comment by sorenhein** [comment]
I agree in principle (there are many other things we could improve about the API, by the way), but as you say, it's a matter of stability.  Thanks for your comment.

**Comment by anntzer** [comment]
There's also plenty of arguments in favor of using signed integers even in such cases, see e.g. https://github.com/ericniebler/stl2/issues/182#issuecomment-287683189 and links therein.

**Comment by df7cb** [comment]
Most often, integers should just be "int", not "prefix_overriding_the_compiler_default int". 
A negative number of threads might be nonsensical, but so are 2^31 threads. In many APIs, -1 is a special value - using unsigned numbers would make that impossible.
