### ISSUE TITLE
does it support 64 bit?

### ISSUE THREAD

**Issue by jhavinay** [dds-bridge/dds#87]
I'm trying to build this on windows 10 with mingw-w64
there is no lib/def file and the dll fails to load. 
any help will be highly appreciated.

**Comment by timanderson** [comment]
It builds successfully in Visual C++ with a 64-bit target though I haven't tested it extensively.

**Comment by jhavinay** [comment]
Thank you. With 2.9.0 shipped dll, windows work fine. Having a problem with linux flavour 64bit with 2.9.0, will open a new issue for that.
