### ISSUE TITLE
misnamed makefile

### ISSUE THREAD

**Issue by samehrlichman** [dds-bridge/dds#92]
It appears that setup.py refers to Makefiles/Makefile_mac_clang but the directory dds/src/Makefiles only contains files like Makefile_mac_clang_static and Makefile_mac_clang_shared.

(This is causing a problem on OSX, obviously)

**Comment by sorenhein** [comment]
Thanks for your comment.  setup.py must be from a project building on DDS, and we must have broadened our Makefiles at some point.  I think the setup.py people will have to fix this on their end.
