### ISSUE TITLE
Incorrect variable in Makefile for Linux shared

### ISSUE THREAD

**Issue by njhammond** [dds-bridge/dds#99]
Use the shared library version on Linux

Running on Ubuntu 19.10

cd src
cp Makefiles/Makefile_linux_shared Makefile
make

Side note: I needed to have boost installed to make this compile:
sudo apt-get install --no-install-recommends libboost-all-dev

make install

# The make install fails because it is using the STATIC variable and not the SHARED
The fix is below: 
change ./src/Makefiles/Makefile_linux_shared at lines 122 and 123 and replace STATIC_LIB with SHARED_LIN

diff Makefile Makefiles/Makefile_linux_shared 
122,123c122,123
< 	cp $(SHARED_LIB) ../test
< 	cp $(SHARED_LIB) ../examples
---
> 	cp $(STATIC_LIB) ../test
> 	cp $(STATIC_LIB) ../examples

**Comment by sorenhein** [comment]
Thanks. Fixed in next release.
